@php($item = $campaign ?? null)
<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><x-input-label for="name" value="Nama campaign *"/><x-text-input id="name" name="name" class="mt-1 w-full" required :value="old('name', $item?->name)"/></div>
    <div><x-input-label for="type" value="Tipe *"/><select id="type" name="type" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['broadcast','transactional','follow_up'] as $value)<option value="{{ $value }}" @selected(old('type', $item?->type ?? 'broadcast') === $value)>{{ $value }}</option>@endforeach</select></div>
    <div><x-input-label for="channel" value="Channel *"/><select id="channel" name="channel" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['email','whatsapp','sms','telegram','internal'] as $value)<option value="{{ $value }}" @selected(old('channel', $item?->channel?->value ?? $item?->channel ?? 'whatsapp') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
    <div><x-input-label for="status" value="Status"/><select id="status" name="status" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['draft','scheduled','paused','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status', $item?->status?->value ?? $item?->status ?? 'draft') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
    <div><x-input-label for="message_template_id" value="Template"/><select id="message_template_id" name="message_template_id" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800"><option value="">Tanpa template</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected((string) old('message_template_id', $item?->message_template_id) === (string) $template->id)>{{ $template->name }}</option>@endforeach</select></div>
    <div><x-input-label for="sender_integration_connection_id" value="Koneksi pengirim"/><select id="sender_integration_connection_id" name="sender_integration_connection_id" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800"><option value="">Pilih nanti</option>@foreach($integrations as $integration)<option value="{{ $integration->id }}" @selected((string) old('sender_integration_connection_id', $item?->sender_integration_connection_id) === (string) $integration->id)>{{ $integration->display_name }}</option>@endforeach</select></div>
    <div><x-input-label for="contact_list_id" value="Daftar kontak"/><select id="contact_list_id" name="contact_list_id" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800"><option value="">Tidak ada</option>@foreach($lists as $list)<option value="{{ $list->id }}" @selected((string) old('contact_list_id', $item?->contact_list_id) === (string) $list->id)>{{ $list->name }}</option>@endforeach</select></div>
    <div><x-input-label for="segment_id" value="Segmen"/><select id="segment_id" name="segment_id" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800"><option value="">Tidak ada</option>@foreach($segments as $segment)<option value="{{ $segment->id }}" @selected((string) old('segment_id', $item?->segment_id) === (string) $segment->id)>{{ $segment->name }}</option>@endforeach</select></div>
    <div><x-input-label for="audience_type" value="Tipe audiens"/><select id="audience_type" name="audience_type" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800"><option value="list">Daftar kontak</option><option value="segment" @selected(old('audience_type', $item?->audience_type) === 'segment')>Segmen</option></select></div>
    <div><x-input-label for="schedule_send_at" value="Jadwal kirim"/><x-text-input id="schedule_send_at" name="schedule_send_at" type="datetime-local" class="mt-1 w-full" :value="old('schedule_send_at', $item?->schedule_send_at?->format('Y-m-d\\TH:i'))"/></div>
</div>
