@php($item = $product ?? null)
<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><x-input-label for="name" value="Nama *"/><x-text-input id="name" name="name" class="mt-1 w-full" required :value="old('name', $item?->name)"/></div>
    <div><x-input-label for="slug" value="Slug *"/><x-text-input id="slug" name="slug" class="mt-1 w-full" required :value="old('slug', $item?->slug)"/></div>
    <div><x-input-label for="type" value="Tipe *"/><select id="type" name="type" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['voucher','course','digital','service','membership'] as $value)<option value="{{ $value }}" @selected(old('type', $item?->type?->value ?? $item?->type ?? 'service') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
    <div><x-input-label for="price" value="Harga *"/><x-text-input id="price" name="price" type="number" min="0" class="mt-1 w-full" required :value="old('price', $item?->price ?? 0)"/></div>
    <div><x-input-label for="status" value="Status"/><select id="status" name="status" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['draft','active','inactive'] as $value)<option value="{{ $value }}" @selected(old('status', $item?->status?->value ?? $item?->status ?? 'draft') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
    <div><x-input-label for="visibility" value="Visibilitas"/><select id="visibility" name="visibility" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['public','login_only','segment_only','hidden_link'] as $value)<option value="{{ $value }}" @selected(old('visibility', $item?->visibility ?? 'public') === $value)>{{ $value }}</option>@endforeach</select></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Deskripsi"/><textarea id="description" name="description" rows="5" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">{{ old('description', $item?->description) }}</textarea></div>
    <div class="md:col-span-2 flex gap-6"><label><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $item?->is_published))> Terbitkan</label><label><input type="hidden" name="is_catalog_visible" value="0"><input type="checkbox" name="is_catalog_visible" value="1" @checked(old('is_catalog_visible', $item?->is_catalog_visible ?? true))> Tampilkan di katalog</label></div>
</div>
