@php($item = $course ?? null)
<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><x-input-label for="title" value="Judul *"/><x-text-input id="title" name="title" class="mt-1 w-full" required :value="old('title', $item?->title)"/></div>
    <div><x-input-label for="slug" value="Slug *"/><x-text-input id="slug" name="slug" class="mt-1 w-full" required :value="old('slug', $item?->slug)"/></div>
    <div class="md:col-span-2"><x-input-label for="summary" value="Ringkasan"/><textarea id="summary" name="summary" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">{{ old('summary', $item?->summary) }}</textarea></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Materi/Deskripsi"/><textarea id="description" name="description" rows="6" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">{{ old('description', $item?->description) }}</textarea></div>
    <div><x-input-label for="difficulty_level" value="Tingkat"/><select id="difficulty_level" name="difficulty_level" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['beginner'=>'Pemula','intermediate'=>'Menengah','advanced'=>'Lanjutan'] as $value=>$label)<option value="{{ $value }}" @selected(old('difficulty_level', $item?->difficulty_level ?? 'beginner') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="estimated_minutes" value="Estimasi menit"/><x-text-input id="estimated_minutes" name="estimated_minutes" type="number" min="1" class="mt-1 w-full" :value="old('estimated_minutes', $item?->estimated_minutes)"/></div>
    <div><x-input-label for="linked_product_id" value="Produk terkait"/><select id="linked_product_id" name="linked_product_id" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800"><option value="">Tidak ada</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string) old('linked_product_id', $item?->linked_product_id) === (string) $product->id)>{{ $product->name }}</option>@endforeach</select></div>
    <div class="flex items-end gap-6"><label><input type="hidden" name="is_free" value="0"><input type="checkbox" name="is_free" value="1" @checked(old('is_free', $item?->is_free))> Gratis</label><label><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $item?->is_published))> Terbitkan</label></div>
</div>
