@php($item = $integration ?? null)
<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><x-input-label for="display_name" value="Nama tampilan *"/><x-text-input id="display_name" name="display_name" class="mt-1 w-full" required :value="old('display_name', $item?->display_name)"/></div>
    <div><x-input-label for="provider_name" value="Nama provider *"/><x-text-input id="provider_name" name="provider_name" class="mt-1 w-full" required :value="old('provider_name', $item?->provider_name)"/></div>
    <div><x-input-label for="provider_category" value="Kategori *"/><select id="provider_category" name="provider_category" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['whatsapp','email','sms','stifin_api','payment','license','storage','webpush'] as $value)<option value="{{ $value }}" @selected(old('provider_category', $item?->provider_category?->value ?? $item?->provider_category) === $value)>{{ $value }}</option>@endforeach</select></div>
    <div><x-input-label for="provider_type" value="Kode provider *"/><x-text-input id="provider_type" name="provider_type" class="mt-1 w-full" required :value="old('provider_type', $item?->provider_type)" placeholder="contoh: starsender"/></div>
    <div><x-input-label for="status" value="Status"/><select id="status" name="status" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800">@foreach(['configured','healthy','degraded','offline','disabled','error'] as $value)<option value="{{ $value }}" @selected(old('status', $item?->status?->value ?? $item?->status ?? 'configured') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
    <div class="flex items-end gap-6"><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $item?->is_active ?? true))> Aktif</label><label><input type="hidden" name="is_primary" value="0"><input type="checkbox" name="is_primary" value="1" @checked(old('is_primary', $item?->is_primary))> Utama</label></div>
    <div class="md:col-span-2"><x-input-label for="credentials_json" value="Kredensial (JSON)"/><textarea id="credentials_json" name="credentials_json" rows="5" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800 font-mono" placeholder='{"token":"..."}'></textarea><p class="text-xs text-gray-500 mt-1">Kosongkan saat edit untuk mempertahankan kredensial lama.</p></div>
    <div class="md:col-span-2"><x-input-label for="config_json" value="Konfigurasi tambahan (JSON)"/><textarea id="config_json" name="config_json" rows="5" class="mt-1 w-full rounded-lg border-gray-300 dark:bg-gray-800 font-mono">{{ old('config_json', $item?->config_json ? json_encode($item->config_json, JSON_PRETTY_PRINT) : '') }}</textarea></div>
</div>
